server:
  port: 8081
jwt:
  secret: Mj@#Im$%ani
  #  expiration: 1440
  expiration: 999999
spring: 
  application:
    name: quAnswer
#  profiles: 
#    active: local
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/quAnswer?retryWrites=true&w=majority
#      database: quAnswer
#      port: 27017
#      host: mongoDb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

user: 
  tags: 
    notification: 
      #cron: "0 */1 * * * *"
      cron: "0 0 2 * * *"
      questionHyperLink: "http://localhost:4200/#/question/details?objectId="

logging:
  level:
     ir.mjimani.basespringboot: DEBUG