server:
  port: 8081
jwt:
  secret: Mj@#Im$%ani
  #  expiration: 1440
  expiration: 999999
spring:
  application:
    name: referensee
  profiles:
    active:
      - prod
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://mjimani:1LexeQUft25dtbXW@cluster0.pysa4.mongodb.net/TestAtlas?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
user: 
  tags: 
    notification: 
      cron: "0 0 2 * * *"
      questionHyperLink: "https://www.referensee.com/en/question/details?objectId="

      
logging:
  level:
     ir.mjimani.basespringboot: ERROR