server:
  port: 8081
jwt:
  secret: Mj@#Im$%ani
  #  expiration: 1440
  expiration: 999999
spring:
  application:
    name: quAnswer
  profiles:
    active:
      - test
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: quAnswer
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

user: 
  tags: 
    notification: 
      cron: "0 */1 * * * *"

logging:
  level:
     ir.mjimani.basespringboot: DEBUG